#!/bin/bash

# Decompile all APKs in the directory
for file in ./*.apk; do
    apktool d -f "$file"
done

# Process each directory generated by apktool
for dir in $(ls -d */); do
    # Create the directory for the opcodes
    mkdir -p "${dir}smali/opcodes"

    # Search for .smali files in the current directory
    FILES=$(find "${dir}smali" -type f -name '*.smali')

    # Extract the opcodes and clean the file
    for file in $FILES; do
        grep -v "[0*.#:}{\"]" "$file" | sed '/^$/d' | sed 's/ //g' | cut -d"," -f1 | sort -u > "${dir}smali/opcodes/opcodes.txt"
    done
done

# Clean the opcodes in multiples steps
for dir in $(ls -d */); do
    # Remove the 'v' prefix followed by a number
    sed "s/v[0-9]//g" "${dir}smali/opcodes/opcodes.txt" > "${dir}smali/opcodes/opcodesv1.txt"
    
    # Remove the 'p' prefix followed by number
    sed "s/p[0-9]//g" "${dir}smali/opcodes/opcodesv1.txt" > "${dir}smali/opcodes/opcodesv2.txt"
    
    # Remove any numbers at the end of the lines
    sed "s/[0-9]$//g" "${dir}smali/opcodes/opcodesv2.txt" > "${dir}smali/opcodes/opcodesv3.txt"
done
